version: '2'

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    links:
     - mysql
    environment:
      WORDPRESS_DB_PASSWORD: {YOUR_DB_PASSWORD}
    volumes:
     - $PWD/wordpress/wp-content/themes/{YOUR_THEME}/:/var/www/html/wp-content/themes/{YOUR_THEME}/
     - $PWD/wordpress/wp-content/uploads/:/var/www/html/wp-content/uploads:rw
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: {YOUR_DB_PASSWORD}